CREATE SEQUENCE IF NOT EXISTS seq_user_id
    INCREMENT BY 1
    NO MAXVALUE
    START WITH 1;

CREATE SEQUENCE IF NOT EXISTS seq_task_id
    INCREMENT BY 1
    NO MAXVALUE
    START WITH 1;

CREATE TABLE tbl_user (
    ID INTEGER NOT NULL PRIMARY KEY DEFAULT nextval('seq_user_id'),
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE tbl_task (
    ID INTEGER NOT NULL PRIMARY KEY DEFAULT nextval('seq_task_id'),
    TITLE VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    TASK_ID INTEGER,
    DATE_EXECUTION DATE NOT NULL,
    DATE_FINALIZATION DATE NOT NULL,
    USER_ID INTEGER NOT NULL,
    CONSTRAINT fk_task_id  FOREIGN KEY (USER_ID) REFERENCES tbl_user (ID)
);
